IQA_description = ["Did Teacher support Students in connecting ideas and positions to build coherence in the discussion about a text?",
				   "Did Teacher press Students to support their contributions with evidence and/or reasoning?",
				   "Did Students’ contributions link to and build on each other during the discussion about a text?",
				   "Did Students support their contributions with text-based evidence?",
				   "Did Students support their contributions with reasoning?"
				   ]

IQA_scoring = ["4: 3+ times during the lesson, Teacher connects Students’ contributions to each other and shows how
ideas/ positions shared during the discussion relate to each other.\n3: Twice during the lesson, Teacher connects Students’ contributions to each other and shows how ideas/ positions shared during the discussion relate to each other.\n2: Once during the lesson, Teacher connects Students’ contributions to each other and shows how ideas/ positions shared during the discussion relate to each other OR The Teacher links contributions to each other, but does not show how ideas/positions relate to each other (re-stating).\n1: The Teacher does not make any effort to link or revoice contributions.",
"4: 3+ times, Teacher asks Students academically relevant Questions, which may include asking Students to provide evidence for their contributions, pressing Students for accuracy, or to explain their reasoning.\n3: Twice, Teacher asks Students academically relevant Questions, which may include asking Students to provide evidence for their contributions, pressing Students for accuracy, or to explain their reasoning.\n2: Once, Teacher asks Students academically relevant Questions, which may include asking Students to provide evidence for their contributions, pressing Students for accuracy, or to explain their reasoning. OR There are superficial, trivial, or formulaic efforts to ask Students to provide evidence for their contributions or to explain their reasoning.\n1: There are no efforts to ask Students to provide evidence for their contributions or to ask Ss to explain their reasoning.",
"4: 3+ times during the lesson, Students connect their contributions to each other and show how
ideas/positions shared during the discussion relate to each other.\n3: Twice during the lesson, Students connect their contributions to each other and show how ideas/positions shared during the discussion relate to each other.\n2: Once during the lesson, Students connect their contributions to each other and show how ideas/positions shared during the discussion relate to each other OR the Students link contributions to each other, but do not show how ideas/positions relate to each other (re-stating).\n1: The Students do not make any effort to link or revoice contributions.",
"4: 3+ times, Students provide specific, accurate, and appropriate evidence for their claims in the form of references to the text.\n3: Twice, Students provide specific, accurate, and appropriate evidence for their claims in the form of references to the text.\n2: Once, Students provide specific, accurate, and appropriate evidence for their claims in the form of references to the text OR There are superficial or trivial efforts to provide evidence.\n1: Students do not back up their claims.",
"4: 3+ times, Students offer extended and clear explanation of their thinking.\n3: Twice, Students offer extended and clear explanation of their thinking.\n2: Once, Students offer extended and clear explanation of their thinking OR There are superficial or trivial efforts to provide explanation.\n1: Students do not explain their thinking or reasoning.
"
]